Use anyhow::Context for easy explanation of library errors.
https://docs.rs/crate/anyhow/latest

```console
$ dinstaller config show`
Error: Connecting to D-Bus address unix:path=/run/d-installer/bus
Error: Anyhow(Connecting to D-Bus address unix:path=/run/d-installer/bus

Caused by:
    0: I/O error: No such file or directory (os error 2)
    1: No such file or directory (os error 2))
```